#Create a Employee
POST  http://localhost:3000/users
Content-Type: application/json

{
    "name": "Kalyan",
    "age":20,
    "email": "kalyan@gmail.com",
    "password": "Seven@One",
    "gdo": "GDO4",
    "role": "Employee"
}


#Create a Admin

POST  http://localhost:3000/users
Content-Type: application/json

{
    "name": "surya",
    "age": 20,
    "email": "surya@gmail.com",
    "password": "three@two",
    "gdo": "GDO2",
    "role":"Admin"
    
}

#get all  goals 
GET http://localhost:3000/goals

#post goal
POST  http://localhost:3000/goals
Content-Type: application/json

{
    "goal": "Learn React Redux",
    "status": "inprogress",
    "date": "2022-05-01",
    "user_id": 3
     
}

#get all users details
GET http://localhost:3000/users

#get all admins
GET http://localhost:3000/admins

#get all user by gdo like GDO1 GDO2 GDO3 or GDO4
GET http://localhost:3000/usersbygdo/GDO1


#get all employee details by gdo like GDO1 GDO2 GDO3 or GDO4
GET http://localhost:3000/employee/GDO1


#get superadmin details
GET http://localhost:3000/superadmin

