#get all users details
GET http://localhost:3040/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs

#get all admins
GET http://localhost:3050/users/admins
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpc1N1cGVyQWRtaW4iOnRydWUsImlhdCI6MTY1NDUxOTc0Nn0.YR07ZSNwp_vmS8iQ_UOOJwUl_MDd01F9MXXD_lzbPOY

GET http://localhost:3050/users/admin/GDO4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpc1N1cGVyQWRtaW4iOnRydWUsImlhdCI6MTY1NDUxOTc0Nn0.YR07ZSNwp_vmS8iQ_UOOJwUl_MDd01F9MXXD_lzbPOY

#get all employee details by gdo like GDO1 GDO2 GDO3 or GDO4
GET http://localhost:3040/users/employee/GDO3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2NTQwODQxMzl9.NhG2pSfo6KDxrJjl8xO96kp-yyMgx9sfQACWGhyyXVw

#get goals based on used id
GET http://localhost:3040/goals/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs

POST http://localhost:3040/login
Content-Type: application/json

{
    "email":"sravani@gmail.com",
    "password":"password@1234"
}

#Create a Employee
POST  http://localhost:3040/register
Content-Type: application/json

{
      "name": "Qpp yu",
      "age":20,
      "email": "lpamk@gmail.com",
      "password": "LF@t3EF3",
      "skills":"Python",
      "gdo": "GDO3",
      "mobile":"5432167890",
      "role": "Employee"
      
}


#Create a Admin
POST  http://localhost:3040/register
Content-Type: application/json

{
    "name": "King",
    "age": 20,
    "email": "king@gmail.com",
    "password": "tH2rE1e@two",
    "skills":"java,C,Python",
    "mobile":"1234509876",    
    "gdo": "GDO4",
    "role":"Admin"
    
}

#get all  goals 
GET http://localhost:3040/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs

#delete goal by goal id
DELETE  http://localhost:3040/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs
Content-Type: application/json

{
    "id":22
}

#post goal

POST  http://localhost:3040/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs
Content-Type: application/json

{
    "goal": "View all Employee goals",
    "status": "Inprogress",
    "date": "2022-06",
    "user_id":1
     
}


#get goal by month and year
GET http://localhost:3040/goals/byDate/7/2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs

#get goals by employee id , month and year
GET http://localhost:3050/goals/userid/1/2022-06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQwODAwMzF9.Hi7hq0VsS-Ujyl8Mz8xLiiKKecK8AZ5NBc_0P7z_Qgs



PUT http://localhost:3040/goals/editgoal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTcxNjQxfQ.o_f2h1_DJA45_SN_0hJsmxL7JwKxkoPbWquNDaXZDz4
Content-Type: application/json

{
    "id":12,
    "goal":"Learn React",
    "status":"Completed"
}

PUT http://localhost:3040/goals/editstatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTcxNjQxfQ.o_f2h1_DJA45_SN_0hJsmxL7JwKxkoPbWquNDaXZDz4
Content-Type: application/json

{
    "id":2,
    "status":"Inprogress"
}
